"""empty message

Revision ID: 8782e77e72a8
Revises: 995a9f54e2f8
Create Date: 2021-09-04 23:43:22.480360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8782e77e72a8'
down_revision = '995a9f54e2f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'menu_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('platform', 'menu_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('platform', 'report_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('platform', 'report_id',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('platform', 'menu_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('category', 'menu_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
