"""empty message

Revision ID: 995a9f54e2f8
Revises: 6f1bfe25e29a
Create Date: 2021-09-04 22:22:44.219581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995a9f54e2f8'
down_revision = '6f1bfe25e29a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('menu_value', sa.Integer(), nullable=True))
    op.add_column('platform', sa.Column('menu_value', sa.Integer(), nullable=True))
    op.add_column('platform', sa.Column('report_id', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform', 'report_id')
    op.drop_column('platform', 'menu_value')
    op.drop_column('category', 'menu_value')
    # ### end Alembic commands ###
